#!/bin/bash
# Regenerates THIRD_PARTY_LICENSES.md from what is ACTUALLY DISTRIBUTED:
# the Go modules linked into the binary (read back off a probe build with
# `go version -m`, so the list can never drift from go.mod guesswork) plus the
# third-party assets embedded from internal/web/assets (htmx, IBM Plex), whose
# license texts are vendored beside them in internal/web/assets/vendor/.
#
# For each module it emits EVERY license/notice file that module ships (some
# carry several — modernc.org/libc has LICENSE plus LICENSE-3RD-PARTY.md), and
# if none of them carries a copyright LINE it extracts one from the module's
# source, so MIT/BSD attribution is never silently dropped.
#
# Usage: scripts/gen-third-party-licenses.sh [output-path]
#   Default output THIRD_PARTY_LICENSES.md. `make notices-check` runs it to a
#   temp file and diffs, so a stale committed copy fails the release.
set -euo pipefail
# Byte-order sorting/grep everywhere so the output is identical regardless of
# the runner's locale (a UTF-8 collation would order some inputs differently).
export LC_ALL=C
cd "$(git rev-parse --show-toplevel)"

OUT=${1:-THIRD_PARTY_LICENSES.md}
MODCACHE=$(go env GOMODCACHE)
PROBE=$(mktemp)
trap 'rm -f "$PROBE"' EXIT

CGO_ENABLED=0 go build -o "$PROBE" .

# emit_file <path> <heading>: a titled fenced block, GUARANTEEING a trailing
# newline before the closing fence (a license lacking a final newline would
# otherwise glue ``` onto its last line and break the Markdown).
emit_file() {
	local path=$1 heading=$2
	echo
	echo "### $heading"
	echo
	echo '```'
	cat "$path"
	[[ -n "$(tail -c1 "$path")" ]] && echo # add a newline only if the file lacks one
	echo '```'
}

# license_files <dir>: every top-level license/notice/authors file, sorted.
license_files() {
	local dir=$1
	find "$dir" -maxdepth 1 -type f \( \
		-iname 'LICENSE*' -o -iname 'COPYING*' -o -iname 'NOTICE*' \
		-o -iname 'PATENTS*' -o -iname 'AUTHORS*' -o -iname '*-LICENSE' \
		\) | sort
}

emit_module() {
	local title=$1 dir=$2
	echo
	echo "---"
	echo
	echo "## $title"
	local found=0 has_copyright=0 f
	while IFS= read -r f; do
		[[ -z "$f" ]] && continue
		found=1
		emit_file "$f" "$(basename "$f")"
		# A real copyright LINE carries a year — the MIT boilerplate phrase
		# "the above copyright notice" does not, so it must not mask a
		# genuinely missing notice.
		if grep -qiE 'copyright.*[12][0-9]{3}' "$f"; then has_copyright=1; fi
	done < <(license_files "$dir")
	if [[ "$found" = 0 ]]; then
		echo "ERROR: no license file found in $dir" >&2
		exit 1
	fi
	if [[ "$has_copyright" = 0 ]]; then
		local cline
		# Walk .go files in SORTED order (not grep -r's readdir order) so the
		# "first copyright line" is deterministic across machines — otherwise
		# the notices-check gate fails on an unrelated runner.
		cline=$(find "$dir" -name '*.go' -type f 2>/dev/null | sort \
			| xargs -r grep -hi copyright 2>/dev/null \
			| grep -m1 -E '[12][0-9]{3}' | sed 's#^[[:space:]/*]*##' || true)
		if [[ -n "$cline" ]]; then
			echo
			echo "### Copyright (from source headers)"
			echo
			echo '```'
			echo "$cline"
			echo '```'
		fi
	fi
}

{
	echo "# Third-party licenses"
	echo
	echo "idlerthing itself is licensed under the GNU AGPL-3.0-or-later (see LICENSE)."
	echo "The distributed binary statically links the Go modules below and embeds the"
	echo "front-end assets below. Every license and notice file each one ships is"
	echo "reproduced here in full."
	echo
	echo "Generated by scripts/gen-third-party-licenses.sh — regenerate after any"
	echo "dependency or bundled-asset change (\`make notices-check\`, run by the release"
	echo "workflow, fails if this is stale); do not edit by hand."

	# The Go standard library and runtime are statically linked in, but
	# `go version -m` lists only third-party modules — emit GOROOT's license
	# (and the PATENTS grant) explicitly.
	emit_module "Go standard library and runtime (BSD-3-Clause)" "$(go env GOROOT)"

	go version -m "$PROBE" | awk '$1=="dep"{print $2"@"$3}' | sort | while IFS= read -r mod; do
		emit_module "$mod" "$MODCACHE/$mod"
	done

	# Embedded front-end assets. Their upstreams ship no license file inside
	# the artifact we vendored (htmx.min.js carries no header; woff2 is
	# binary), so the texts live in internal/web/assets/vendor/ next to them —
	# whoever updates an asset updates its license in the same commit.
	for f in internal/web/assets/vendor/*.LICENSE; do
		[[ -e "$f" ]] || continue
		echo
		echo "---"
		echo
		echo "## Embedded asset: $(basename "$f" .LICENSE)"
		emit_file "$f" "$(basename "$f")"
	done
} >"$OUT"

echo "wrote $OUT ($(wc -c <"$OUT") bytes)"
